#!/usr/bin/env bash
# installing and configuring nginx on a server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R $USER:$USER /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
