#!/usr/bin/env bash
# installing and configuring nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
update="\\\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"
sudo sed -i "55i $update" /etc/nginx/sites-enabled/default
sudo service nginx start
