#!/usr/bin/env bash
# Installing and configuring load balancer HAproxy

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get -y install haproxy=2.6.\*
sudo sed -i '10i\\nENABLED=1\n' /etc/default/haproxy
balancer="\\\nfrontend Load_Balancer\n \tbind *:80\n \tmode http\n \tdefault_backend Web_Servers\n"
webservers="\\nbackend Web_Servers\n \tbalance roundrobin\n \tserver 82022-web-01 54.82.178.149:80 check\n \tserver 82022-web-02 54.160.78.46:80 check\n"
sudo sed -i "\$a $balancer\n$webservers" /etc/haproxy/haproxy.cfg
sudo service haproxy reload
