#!/usr/bin/env bash
# Installing and configuring load balancer HAproxy

sudo apt-get update -y
sudo apt-get install haproxy -y
sudo sed -i '10i\\nENABLED=1\n' /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg
echo "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout client 10000
    timeout connect 5000
    timeout server 10000
    timeout http-request 10s

frontend Load_Balancer
    bind *:80
    default_backend myservers

backend myservers
    balance roundrobin
    server 82022-web-01 54.82.178.149:80 check
    server 82022-web-02 54.160.78.46:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo systemctl haproxy restart
