#!/usr/bin/env bash
# configuring an nginx server to listen to port 80
apt-get update -y
apt-get install curl -y
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[\:\:\]\:8080/listen \[\:\:\]\:80/" /etc/nginx/sites-enabled/default
service nginx restart
