#!/usr/bin/env bash
# displays a list of currently running processes
# shellcheck disable=SC2009
# -a - to show all processes
# u - user oriented format
# x - include TTY
# f - process heirarchy

ps -auxf | grep bash
