#!/usr/bin/env bash
# script displays 1 to 100 but for numbers divisible by 3
# it displays Fizz, for numbers divisible by 5 it displays Buzz and
# for numbers divisible by both, it displays FizzBuzz

for i in {1..100}
do
	if (( i % 3 == 0  &&  i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $i
	fi
done
