#!/usr/bin/env bash
# script to display the contents of the file /etc/passwd
# only showing username, user id and home directory path

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
