#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but with while loop
# and printing hi after the 9th time

i=0
while [ $i -lt 10 ];
do
	if [ $i = 3 ]
	then
	# print bad luck after 4th i
		echo "bad luck"
	elif [ $i = 7 ]
	then
	# print good luck after 8th i
		echo "good luck"
	else
	# print Best school for the other times
	echo "Best School"
	fi
	((i++))
done
