#!/usr/bin/env bash
# this script gives information about the school file

if [ -e "school" ]
# if the school file exists
then
	echo "school file exists"
	if [ -s "school" ]
	# if the school file size is not zero
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	# if the school file is a regular file
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
